# Generated by Django 5.0.6 on 2026-03-29 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('TRANSACCION', 'Movimiento Financiero'), ('ESTADO', 'Cambio de Estado'), ('INFO', 'Actualización de Datos')], max_length=20)),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('transaccion_id', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='transacciones.categoriatransaccion')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Categorías',
                'ordering': ['-fecha'],
            },
        ),
    ]
