# Generated by Django 5.0.6 on 2026-03-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_movimientocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_audit', to='transacciones.transaccion')),
            ],
            options={
                'verbose_name_plural': 'Historial de Transacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
