# Generated by Django 5.0.6 on 2026-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_historialtransaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocategoria',
            name='monto',
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='estado_categoria',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocategoria',
            name='estado_categoria',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
