# Generated by Django 5.0.6 on 2026-03-20 03:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DINERO', 'Dinero en Efectivo/Banco'), ('BIEN', 'Bien/Activo Fijo')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_capital', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Capital',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('vida_util_anios', models.PositiveIntegerField(blank=True, null=True)),
                ('depreciacion_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VENDIDO', 'Vendido')], default='ACTIVO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activos_capital', to='core.empresa')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capital.tipocapital')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
