# Generated by Django 5.0.6 on 2026-03-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_add_default_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='capital.capital')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
