# Generated by Django 5.0.6 on 2026-03-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0003_movimientocapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocapital',
            name='valor_actual_ant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimientocapital',
            name='valor_actual_nvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimientocapital',
            name='valor_inicial_ant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimientocapital',
            name='valor_inicial_nvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
