# Generated by Django 5.0.6 on 2026-04-16 04:14

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolpersonalizado_perfilusuario_rol_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.tenant_logo_path),
        ),
    ]
