# Generated by Django 5.0.6 on 2026-04-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_logo'),
        ('inventario', '0008_almacen_stockalmacen_trasladostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén al que está asignado este colaborador. Gerente puede acceder a todos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_asignados', to='inventario.almacen'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('COLABORADOR', 'Colaborador'), ('VENDEDOR', 'Colaborador (legacy)')], default='COLABORADOR', max_length=20),
        ),
    ]
