# Generated by Django 5.0.6 on 2026-08-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_almacen_from_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('COLABORADOR', 'Colaborador'), ('VENDEDOR', 'Colaborador (legacy)')], default='COLABORADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='DIARIO', max_length=20)),
                ('hora_ejecucion', models.TimeField(default='03:00')),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_respaldo', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_backup', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Backup',
                'db_table': 'core_configuracion_backup',
            },
        ),
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='backups/tenants/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error')], max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_backups', to='core.empresa')),
            ],
            options={
                'db_table': 'core_registro_backup',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
