# Generated by Django 5.0.6 on 2026-03-29 23:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0005_alter_movimientostock_origen'),
        ('servicios', '0005_movimientoservicio'),
        ('ventas', '0003_movimientoestadoventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, help_text='DNI, RUC u otro', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_fiados', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'Clientes Fiados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Venta de Productos'), ('SERVICIO', 'Venta de Servicios')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO_PARCIAL', 'Cobro Parcial'), ('LIQUIDADO', 'Liquidado / Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_limite', models.DateField(blank=True, help_text='¿Para cuándo prometió pagar?', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiados', to='fiados.clientefiado')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiados', to='core.empresa')),
                ('venta_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiado_origen', to='ventas.venta')),
                ('venta_servicio_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiado_origen', to='servicios.ventaservicio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFiadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='fiados.fiado')),
            ],
            options={
                'ordering': ['servicio__nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFiadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='fiados.fiado')),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_restante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='fiados.fiado')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
