# Generated by Django 5.0.6 on 2026-03-30 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiados', '0002_detallefiadoproducto_descuento_fiado_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefiadoservicio',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='detallefiadoservicio',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
