# Generated by Django 5.0.6 on 2026-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiados', '0003_detallefiadoservicio_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialfiado',
            name='total_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
