# Generated by Django 5.0.6 on 2026-03-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiados', '0004_historialfiado_total_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialfiado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_directo', to='fiados.clientefiado'),
        ),
        migrations.AlterField(
            model_name='historialfiado',
            name='fiado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='fiados.fiado'),
        ),
        migrations.AlterField(
            model_name='historialfiado',
            name='saldo_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
