# Generated by Django 5.0.6 on 2026-08-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_movimientoestadocliente_usuario'),
        ('fiados', '0007_fiado_cliente_fk_to_clientes_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiados', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='historialfiado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_fiados', to='clientes.cliente'),
        ),
    ]
