# Generated by Django 5.0.6 on 2026-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('PERSONA_NATURAL', 'Persona Natural'), ('EMPRESA', 'Empresa')], default='PERSONA_NATURAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20),
        ),
    ]
