# Generated by Django 5.0.6 on 2026-03-24 23:41

from django.db import migrations


def crear_publico_general(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    Empresa = apps.get_model('core', 'Empresa')
    
    for empresa in Empresa.objects.all():
        Cliente.objects.get_or_create(
            empresa=empresa,
            numero_documento='00000000',
            defaults={
                'nombre': 'Cliente General',
                'tipo_cliente': 'PERSONA_NATURAL',
                'tipo_documento': 'DNI',
                'activo': True,
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_tipo_cliente_and_more'),
        ('core', '0001_initial'),  # Depend on core for Empresa
    ]

    operations = [
        migrations.RunPython(crear_publico_general),
    ]
