# Generated by Django 5.0.6 on 2026-03-25 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_estado', to='clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Estado de Cliente',
                'ordering': ['-fecha'],
            },
        ),
    ]
