# Generated by Django 5.0.6 on 2026-03-21 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientostock_precio_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='precio_compra_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='precio_compra_nuevo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='precio_venta_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='precio_venta_nuevo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
