# Generated by Django 5.0.6 on 2026-03-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_movimientostock_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='activo_nuevo',
            field=models.BooleanField(blank=True, help_text='Si no es None, indica un cambio de estado activo/inactivo del producto.', null=True),
        ),
    ]
