# Generated by Django 5.0.6 on 2026-03-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_activo_nuevo_movimientostock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='origen',
            field=models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('VENTA', 'Venta'), ('FIADO', 'Fiado (Venta diferida)'), ('AJUSTE', 'Ajuste manual'), ('DEVOLUCION', 'Devolución'), ('MERMA', 'Merma')], max_length=20),
        ),
    ]
