# Generated by Django 5.0.6 on 2026-04-20 06:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_logo'),
        ('inventario', '0007_movimientostock_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock por Almacén',
                'verbose_name_plural': 'Stocks por Almacén',
                'db_table': 'inventario_stock_almacen',
            },
        ),
        migrations.CreateModel(
            name='TrasladoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL_A_SUB', 'Del almacén general a un subalmacén'), ('SUB_A_GENERAL', 'De un subalmacén al almacén general'), ('SUB_A_SUB', 'Entre subalmacenes'), ('AJUSTE', 'Ajuste de inventario (Gerente)')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Traslado de Stock',
                'verbose_name_plural': 'Traslados de Stock',
                'db_table': 'inventario_traslado_stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_general', models.BooleanField(default=False, help_text='True si es el almacén principal/general de la empresa.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'inventario_almacen',
                'ordering': ['-es_general', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén donde ocurrió este movimiento de stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='inventario.almacen'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', '-fecha'], name='inventario__product_082fec_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['almacen', '-fecha'], name='inventario__almacen_a19150_idx'),
        ),
        migrations.AddField(
            model_name='stockalmacen',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='stockalmacen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_por_almacen', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='trasladostock',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='trasladostock',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='trasladostock',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traslados_stock', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='trasladostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='trasladostock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['empresa', 'es_general'], name='inventario__empresa_102569_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalmacen',
            index=models.Index(fields=['almacen', 'producto'], name='inventario__almacen_d09511_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockalmacen',
            unique_together={('almacen', 'producto')},
        ),
        migrations.AddIndex(
            model_name='trasladostock',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_9092e2_idx'),
        ),
        migrations.AddIndex(
            model_name='trasladostock',
            index=models.Index(fields=['producto', '-fecha'], name='inventario__product_362fc9_idx'),
        ),
    ]
