# Generated by Django 5.0.6 on 2026-04-20 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_almacen_stockalmacen_trasladostock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='activo_nuevo',
            field=models.BooleanField(blank=True, help_text='Cambio de estado activo/inactivo del producto.', null=True),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén donde ocurrió este movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='inventario.almacen'),
        ),
        migrations.CreateModel(
            name='HistorialAsignacionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('almacen_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_salidas', to='inventario.almacen')),
                ('almacen_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_entradas', to='inventario.almacen')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones_almacen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Asignación de Almacén',
                'verbose_name_plural': 'Historial de Asignaciones de Almacén',
                'db_table': 'inventario_historial_asignacion_almacen',
                'ordering': ['-fecha'],
            },
        ),
    ]
