# Generated by Django 5.0.6 on 2026-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_historial_asignacion_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='origen',
            field=models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('VENTA', 'Venta'), ('FIADO', 'Fiado (Venta diferida)'), ('AJUSTE', 'Ajuste manual'), ('DEVOLUCION', 'Devolución'), ('MERMA', 'Merma (General)'), ('CADUCIDAD', 'Caducidad/Vencimiento'), ('EXTRAVIO', 'Extravío o Robo'), ('ROTURA', 'Rotura o Daño')], max_length=20),
        ),
    ]
