# Generated by Django 5.0.6 on 2026-08-03 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_perfilusuario_rol_configuracionbackup_and_more'),
        ('inventario', '0011_remove_almacen_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='activo_nuevo',
            field=models.BooleanField(blank=True, help_text='Cambio de estado activo/inactivo del producto.', null=True),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', '-fecha'], name='inventario__product_082fec_idx'),
        ),
    ]
