# Generated by Django 5.0.6 on 2026-04-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_movimientoestadocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_compra',
            field=models.CharField(choices=[('PROVEEDOR', 'Compra a Proveedor'), ('MINORISTA', 'Compra al por menor')], db_index=True, default='PROVEEDOR', max_length=20),
        ),
    ]
