# Generated by Django 5.0.6 on 2026-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_compra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoestadocompra',
            name='razon_detalle',
            field=models.TextField(blank=True, help_text='Detalle libre del motivo de cancelación', null=True),
        ),
        migrations.AddField(
            model_name='movimientoestadocompra',
            name='razon_tag',
            field=models.CharField(blank=True, choices=[('CONFUSION', 'Confusión en el pedido'), ('ARREPENTIMIENTO', 'El cliente se arrepintió'), ('SIN_STOCK', 'Sin stock disponible'), ('PRECIO', 'Desacuerdo en el precio'), ('DUPLICADO', 'Registro duplicado'), ('ERROR_SISTEMA', 'Error del sistema'), ('OTRO', 'Otro motivo')], max_length=30, null=True),
        ),
    ]
