# Generated by Django 5.0.6 on 2026-04-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_razon_cancelacion'),
        ('inventario', '0010_alter_movimientostock_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_almacen', to='inventario.almacen'),
        ),
    ]
