# Generated by Django 5.0.6 on 2026-03-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación del proveedor'), ('ESTADO_ACTIVO', 'Cambio a estado Activo'), ('ESTADO_INACTIVO', 'Cambio a estado Inactivo'), ('CONTRATO_SI', 'Contrato firmado'), ('CONTRATO_NO', 'Contrato finalizado'), ('OTRO', 'Otra modificación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo_nuevo', models.BooleanField(default=True)),
                ('contrato_nuevo', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Proveedor',
                'ordering': ['-fecha'],
            },
        ),
    ]
