# Generated by Django 5.0.6 on 2026-03-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_movimientoproveedor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('nombre', 'identificador')},
        ),
    ]
