# Generated by Django 5.0.6 on 2026-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_proveedor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='identificador',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
