# Generated by Django 5.0.6 on 2026-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_proveedor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='RUC', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('PERSONA_NATURAL', 'Persona Natural'), ('EMPRESA', 'Empresa')], default='PERSONA_NATURAL', max_length=20),
        ),
    ]
