# Generated by Django 5.0.6 on 2026-03-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('proveedores', '0006_proveedor_tipo_documento_proveedor_tipo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='identificador',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'identificador'), name='unique_proveedor_per_empresa'),
        ),
    ]
