# Generated by Django 5.0.6 on 2026-03-24 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaservicio',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ventaservicio',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventaservicio',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
