# Generated by Django 5.0.6 on 2026-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_ventaservicio_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaservicio',
            name='numero_comprobante_simple',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
