# Generated by Django 5.0.6 on 2026-03-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_ventaservicio_numero_comprobante_simple'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEstadoVentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('venta_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_estado', to='servicios.ventaservicio')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Estado de Venta de Servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
