# Generated by Django 5.0.6 on 2026-03-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('servicios', '0004_movimientoestadoventaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('AJUSTE', 'Ajuste de Precios/Costos'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo_anterior', models.BooleanField(blank=True, null=True)),
                ('activo_nuevo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_servicio', to='core.empresa')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='servicios.servicio')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
