# Generated by Django 5.0.6 on 2026-04-24 07:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfilusuario_almacen_configuracionbackup_and_more'),
        ('proveedores', '0009_movimientoproveedor_usuario'),
        ('servicios', '0008_razon_cancelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/servicios_compras/')),
                ('servicio_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_comprobante_simple', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_servicio', to='core.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_contratados', to='proveedores.proveedor')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_rel', to='servicios.servicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEstadoCompraServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('razon_tag', models.CharField(blank=True, choices=[('CONFUSION', 'Confusión en el pedido'), ('ARREPENTIMIENTO', 'El usuario se arrepintió'), ('INCUMPLIMIENTO', 'Proveedor no cumplió'), ('PRECIO', 'Desacuerdo en el precio'), ('DUPLICADO', 'Registro duplicado'), ('ERROR_SISTEMA', 'Error del sistema'), ('OTRO', 'Otro motivo')], max_length=30, null=True)),
                ('razon_detalle', models.TextField(blank=True, help_text='Detalle libre del motivo de cancelación', null=True)),
                ('compra_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_estado', to='servicios.compraservicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Estado de Compra de Servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
