# Generated by Django 5.0.6 on 2026-04-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('EMPRENDEDOR', 'Emprendedor'), ('EMPRESARIO', 'Empresario')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tiene_roles_avanzados', models.BooleanField(default=False)),
                ('cobra_por_asiento', models.BooleanField(default=False)),
                ('precio_asiento_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('asientos_contratados', models.PositiveIntegerField(default=1)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='clientes_saas.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suscripciones.plan')),
            ],
        ),
    ]
