# Generated by Django 5.0.6 on 2026-05-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='culqi_charge_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('SANDBOX', 'Sandbox')], default='SANDBOX', max_length=20),
        ),
    ]
