# Generated by Django 5.0.6 on 2026-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_comprobante_simple',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
