# Generated by Django 5.0.6 on 2026-04-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_movimientoestadoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20),
        ),
    ]
