# Generated by Django 5.0.6 on 2026-04-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_movimientostock_origen'),
        ('ventas', '0007_razon_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='inventario.almacen'),
        ),
    ]
