# Generated by Django 5.0.6 on 2026-04-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Tenant (Negocio)', 'verbose_name_plural': 'Tenants (Negocios)'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email del Gerente principal que creó y administra este tenant.', max_length=254, null=True, unique=True),
        ),
    ]
